/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 leaf.gltf 
Author: dravid1852 (https://sketchfab.com/dravid1852)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/leaf-42f3db9df1f14492852b11574daeeb3e
Title: Leaf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Leaf(props) {
	const { nodes, materials } = useGLTF("/assets/leaf.gltf");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.Leaf}
				position={[-1.487, 0, 1.263]}
			/>
		</group>
	);
}

useGLTF.preload("/leaf.gltf");
